name: shelf_response_formatter
version: 0.1.0
description: >
  Simple extensible response formatter which detects appropriate response format
  and serializes data accordingly.
homepage: https://github.com/bwu-dart/shelf_response_formatter
authors:
- Günter Zöchbauer <guenter@gzoechbauer.com>
- Thomas Profelt <tom@octobyte.at>
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  shelf: '>=0.6.0 <0.7.0'
  xml: '>=2.1.0 <3.0.0'

dev_dependencies:
  unittest: '>=0.9.0 <0.13.0'
  analyzer: '>=0.24.0 <0.26.0'
  grinder: '>=0.7.0-dev.1 <0.8.0'
  linter: '>=0.0.2 <0.1.0'
  unittest: any

